import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'common/concepts/serverless',
        'common/concepts/scale-to-zero',
        'common/concepts/global-replication',
        'common/concepts/access-anywhere',
      ],
    },
    {
      type: 'category',
      label: 'Help',
      items: [
        {
          type: 'category',
          label: 'Account & Teams',
          items: [
            'common/account/createaccount',
            'common/account/teams',
            'common/account/developerapi',
            'common/account/addapaymentmethod',
            'common/account/awsmarketplace',
            'common/account/costexplorer',
            'common/account/paymenthistory',
            'common/account/auditlogs',
            'common/account/faq',
          ],
        },
        'common/help/support',
        'common/help/prosupport',
        'common/help/sla',
        'common/help/uptime',
        'common/help/legal',
        'common/help/compliance',
        'common/help/integration',
      ],
    },
    {
      type: 'category',
      label: 'Redis',
      items: [
        {
          type: 'category',
          label: 'Overall',
          items: [
            'redis/overall/getstarted',
            'redis/overall/pricing',
            'redis/overall/rediscompatibility',
            'redis/overall/changelog',
            'redis/overall/usecases',
            'redis/overall/compare',
            'redis/overall/enterprise',
          ],
        },
        {
          type: 'category',
          label: 'Quickstarts',
          items: [
            'redis/quickstarts/aws-lambda',
            {
              type: 'category',
              label: 'Vercel Functions',
              items: [
                'redis/quickstarts/vercel-functions-app-router',
                'redis/quickstarts/vercel-functions-pages-router',
              ],
            },
            {
              type: 'category',
              label: 'Next.js 14',
              items: [
                'redis/quickstarts/nextjs-app-router',
                'redis/quickstarts/nextjs-pages-router',
              ],
            },
            {
              type: 'category',
              label: 'SST',
              items: [
                'redis/quickstarts/sst-v2',
                'redis/quickstarts/ion',
              ],
            },
            {
              type: 'category',
              label: 'Python',
              items: [
                'redis/quickstarts/fastapi',
                'redis/quickstarts/flask',
                'redis/quickstarts/django',
                'redis/quickstarts/python-aws-lambda',
                'redis/quickstarts/vercel-python-runtime',
              ],
            },
            'redis/quickstarts/laravel',
            'redis/quickstarts/azure-functions',
            'redis/quickstarts/google-cloud-functions',
            'redis/quickstarts/elixir',
            'redis/quickstarts/fly',
            'redis/quickstarts/cloudflareworkers',
            'redis/quickstarts/fastlycompute',
            'redis/quickstarts/digitalocean',
            'redis/quickstarts/supabase',
            'redis/quickstarts/deno-deploy',
            'redis/quickstarts/koyeb',
          ],
        },
        {
          type: 'category',
          label: 'Features',
          items: [
            'redis/features/globaldatabase',
            'redis/features/restapi',
            'redis/features/backup',
            'redis/features/durability',
            'redis/features/replication',
            'redis/features/eviction',
            'redis/features/security',
            'redis/features/consistency',
          ],
        },
        {
          type: 'category',
          label: 'SDKs',
          items: [
            {
              type: 'category',
              label: 'Typescript',
              items: [
                'redis/sdks/ts/overview',
                'redis/sdks/ts/getstarted',
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    'redis/sdks/ts/commands/overview',
                    {
                      type: 'category',
                      label: 'Auth',
                      items: [
                        'redis/sdks/ts/commands/auth/echo',
                        'redis/sdks/ts/commands/auth/ping',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Bitmap',
                      items: [
                        'redis/sdks/ts/commands/bitmap/bitcount',
                        'redis/sdks/ts/commands/bitmap/bitop',
                        'redis/sdks/ts/commands/bitmap/bitpos',
                        'redis/sdks/ts/commands/bitmap/getbit',
                        'redis/sdks/ts/commands/bitmap/setbit',
                      ],
                    },
                    // Add other command categories similarly...
                  ],
                },
                'redis/sdks/ts/deployment',
                {
                  type: 'category',
                  label: 'Pipelining',
                  items: [
                    'redis/sdks/ts/pipelining/pipeline-transaction',
                    'redis/sdks/ts/pipelining/auto-pipeline',
                  ],
                },
                'redis/sdks/ts/advanced',
                'redis/sdks/ts/retries',
                'redis/sdks/ts/troubleshooting',
                'redis/sdks/ts/developing',
              ],
            },
            {
              type: 'category',
              label: 'Python',
              items: [
                'redis/sdks/py/overview',
                'redis/sdks/py/gettingstarted',
                'redis/sdks/py/features',
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    'redis/sdks/py/commands/overview',
                    {
                      type: 'category',
                      label: 'Auth',
                      items: [
                        'redis/sdks/py/commands/auth/echo',
                        'redis/sdks/py/commands/auth/ping',
                      ],
                    },
                    // Add other command categories similarly...
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Ratelimit (TS)',
              items: [
                'redis/sdks/ratelimit-ts/overview',
                'redis/sdks/ratelimit-ts/gettingstarted',
                'redis/sdks/ratelimit-ts/methods',
                'redis/sdks/ratelimit-ts/features',
                'redis/sdks/ratelimit-ts/traffic-protection',
                'redis/sdks/ratelimit-ts/algorithms',
                'redis/sdks/ratelimit-ts/costs',
                {
                  type: 'category',
                  label: 'Integrations',
                  items: [
                    {
                      type: 'category',
                      label: 'Strapi',
                      items: [
                        'redis/integrations/ratelimit/strapi/getting-started',
                        'redis/integrations/ratelimit/strapi/configurations',
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Ratelimit (PY)',
              items: [
                'redis/sdks/ratelimit-py/overview',
                'redis/sdks/ratelimit-py/gettingstarted',
                'redis/sdks/ratelimit-py/features',
                'redis/sdks/ratelimit-py/algorithms',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'How To',
          items: [
            'redis/howto/connectclient',
            'redis/howto/connectwithupstashredis',
            'redis/howto/upgradedatabase',
            'redis/howto/metricsandcharts',
            'redis/howto/monitoryourusage',
            'redis/howto/importexport',
            'redis/howto/keyspacenotifications',
            'redis/howto/ipallowlist',
            'redis/howto/readyourwrites',
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            'redis/howto/datadog',
            'redis/integrations/prometheus',
            'redis/integrations/bullmq',
            'redis/integrations/sidekiq',
            'redis/howto/vercelintegration',
            'redis/integrations/replit-templates',
            'redis/howto/emqxintegration',
            'redis/integrations/celery',
          ],
        },
        {
          type: 'category',
          label: 'Tutorials',
          items: [
            'redis/tutorials/python_realtime_chat',
            'redis/tutorials/python_session',
            'redis/tutorials/python_rate_limiting',
            'redis/tutorials/python_multithreading',
            'redis/tutorials/python_fastapi_caching',
            'redis/tutorials/python_url_shortener',
            'redis/tutorials/api_with_cdk',
            'redis/tutorials/auto_complete_with_serverless_redis',
            'redis/tutorials/aws_app_runner_with_redis',
            'redis/tutorials/cloud_run_sessions',
            'redis/tutorials/cloudflare_workers_with_redis',
            'redis/tutorials/cloudflare_websockets_redis',
            'redis/tutorials/edge_leaderboard',
            'redis/tutorials/express_session',
            'redis/tutorials/goapi',
            'redis/tutorials/histogram',
            'redis/tutorials/job_processing',
            'redis/tutorials/nextjs_with_redis',
            'redis/tutorials/notification',
            'redis/tutorials/nuxtjs_with_redis',
            'redis/tutorials/pythonapi',
            'redis/tutorials/rate-limiting',
            'redis/tutorials/redisson',
            'redis/tutorials/roadmapvotingapp',
            'redis/tutorials/serverless_java_redis',
            'redis/tutorials/using_aws_sam',
            'redis/tutorials/using_google_cloud_functions',
            'redis/tutorials/using_serverless_framework',
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          items: [
            'redis/troubleshooting/command_count_increases_unexpectedly',
            'redis/troubleshooting/no_auth',
            'redis/troubleshooting/http_unauthorized',
            'redis/troubleshooting/econn_reset',
            'redis/troubleshooting/max_concurrent_connections',
            'redis/troubleshooting/max_request_size_exceeded',
            'redis/troubleshooting/max_record_size_exceeded',
            'redis/troubleshooting/max_key_size_exceeded',
            'redis/troubleshooting/db_capacity_quota_exceeded',
            'redis/troubleshooting/max_daily_request_limit',
            'redis/troubleshooting/stream_pel_limit',
          ],
        },
        {
          type: 'category',
          label: 'Help',
          items: [
            'redis/help/faq',
            {
              type: 'category',
              label: 'Support',
              items: [
                'redis/help/support',
                'redis/help/prosupport',
                'redis/help/sla',
                'redis/help/uptime',
                'redis/help/legal',
                'redis/help/compliance',
                'redis/help/integration',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Vector',
      items: [
        {
          type: 'category',
          label: 'Overall',
          items: [
            'vector/overall/getstarted',
            'vector/overall/whatisvector',
            'vector/overall/pricing',
            'vector/overall/changelog',
          ],
        },
        {
          type: 'category',
          label: 'Features',
          items: [
            'vector/features/algorithm',
            'vector/features/similarityfunctions',
            'vector/features/hybridindexes',
            'vector/features/sparseindexes',
            'vector/features/metadata',
            'vector/features/filtering',
            'vector/features/embeddingmodels',
            'vector/features/namespaces',
            'vector/features/resumablequery',
          ],
        },
        {
          type: 'category',
          label: 'REST API',
          items: [
            'vector/api/get-started',
            {
              type: 'category',
              label: 'Endpoints',
              items: [
                'vector/api/endpoints/upsert',
                'vector/api/endpoints/upsert-data',
                'vector/api/endpoints/query',
                'vector/api/endpoints/query-data',
                {
                  type: 'category',
                  label: 'Resumable Query',
                  items: [
                    'vector/api/endpoints/resumable-query/start-with-vector',
                    'vector/api/endpoints/resumable-query/start-with-data',
                    'vector/api/endpoints/resumable-query/resume',
                    'vector/api/endpoints/resumable-query/stop',
                  ],
                },
                'vector/api/endpoints/fetch',
                'vector/api/endpoints/fetch-random',
                'vector/api/endpoints/range',
                'vector/api/endpoints/delete',
                'vector/api/endpoints/update',
                'vector/api/endpoints/reset',
                'vector/api/endpoints/info',
                'vector/api/endpoints/list-namespaces',
                'vector/api/endpoints/delete-namespace',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'SDKs',
          items: [
            {
              type: 'category',
              label: 'Typescript',
              items: [
                'vector/sdks/ts/getting-started',
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    'vector/sdks/ts/commands/upsert',
                    'vector/sdks/ts/commands/query',
                    'vector/sdks/ts/commands/resumable-query',
                    'vector/sdks/ts/commands/fetch',
                    'vector/sdks/ts/commands/delete',
                    'vector/sdks/ts/commands/range',
                    'vector/sdks/ts/commands/reset',
                    'vector/sdks/ts/commands/info',
                  ],
                },
                'vector/sdks/ts/contributing',
              ],
            },
            {
              type: 'category',
              label: 'Python',
              items: [
                'vector/sdks/py/gettingstarted',
                'vector/sdks/py/features',
                {
                  type: 'category',
                  label: 'Example Calls',
                  items: [
                    'vector/sdks/py/example_calls/upsert',
                    'vector/sdks/py/example_calls/query',
                    'vector/sdks/py/example_calls/resumable-query',
                    'vector/sdks/py/example_calls/range',
                    'vector/sdks/py/example_calls/fetch',
                    'vector/sdks/py/example_calls/delete',
                    'vector/sdks/py/example_calls/update',
                    'vector/sdks/py/example_calls/reset',
                    'vector/sdks/py/example_calls/info',
                  ],
                },
              ],
            },
            'vector/sdk/semantic-cache-js',
            'vector/sdk/semantic-cache-py',
            'vector/sdk/gosdk',
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            'vector/integrations/ai-sdk',
            'vector/integrations/langchain',
            'vector/integrations/llamaindex',
            'vector/integrations/llamaparse',
            'vector/integrations/flowise',
            'vector/integrations/langflow',
          ],
        },
        {
          type: 'category',
          label: 'Tutorials',
          items: [
            'vector/tutorials/semantic_search',
            'vector/tutorials/langchain',
            'vector/tutorials/llamaindex',
            'vector/tutorials/llamaparse',
            'vector/tutorials/huggingface-embeddings',
            'vector/tutorials/gradio-application',
          ],
        },
        {
          type: 'category',
          label: 'Examples',
          items: ['vector/examples'],
        },
        {
          type: 'category',
          label: 'Help',
          items: ['vector/help/faq'],
        },
      ],
    },
    {
      type: 'category',
      label: 'QStash',
      items: [
        {
          type: 'category',
          label: 'Overall',
          items: [
            'qstash/overall/getstarted',
            'qstash/overall/pricing',
            'qstash/overall/apiexamples',
            'qstash/overall/compare',
            'qstash/overall/changelog',
          ],
        },
        {
          type: 'category',
          label: 'Quickstarts',
          items: [
            'qstash/quickstarts/vercel-nextjs',
            'qstash/quickstarts/python-vercel',
            'qstash/quickstarts/cloudflare-workers',
            'qstash/quickstarts/aws-lambda/nodejs',
            'qstash/quickstarts/aws-lambda/python',
            'qstash/quickstarts/deno-deploy',
            'qstash/quickstarts/fly-io/go',
          ],
        },
        {
          type: 'category',
          label: 'Features',
          items: [
            'qstash/features/background-jobs',
            'qstash/features/retry',
            'qstash/features/schedules',
            'qstash/features/queues',
            'qstash/features/delay',
            'qstash/features/url-groups',
            'qstash/features/batch',
            'qstash/features/callbacks',
            'qstash/features/dlq',
            'qstash/features/deduplication',
            'qstash/features/security',
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            'qstash/integrations/llm',
            'qstash/integrations/anthropic',
            'qstash/integrations/resend',
            'qstash/integrations/pipedream',
          ],
        },
        {
          type: 'category',
          label: 'How To',
          items: [
            'qstash/howto/publishing',
            'qstash/howto/url-group-endpoint',
            'qstash/howto/handling-failures',
            'qstash/howto/receiving',
            'qstash/howto/local-development',
            'qstash/howto/local-tunnel',
            'qstash/howto/signature',
            'qstash/howto/delete-schedule',
            'qstash/howto/reset-token',
            'qstash/howto/roll-signing-keys',
            'qstash/howto/debug-logs',
            'qstash/howto/kafka',
            'qstash/recipes/periodic-data-updates',
          ],
        },
        {
          type: 'category',
          label: 'REST API',
          items: [
            'qstash/api/authentication',
            {
              type: 'category',
              label: 'Messages',
              items: [
                'qstash/api/publish',
                'qstash/api/enqueue',
                'qstash/api/messages/batch',
                'qstash/api/messages/get',
                'qstash/api/messages/cancel',
                'qstash/api/messages/bulk-cancel',
              ],
            },
            {
              type: 'category',
              label: 'URL Groups',
              items: [
                'qstash/api/url-groups/add-endpoint',
                'qstash/api/url-groups/get',
                'qstash/api/url-groups/list',
                'qstash/api/url-groups/remove-endpoint',
                'qstash/api/url-groups/remove',
              ],
            },
            {
              type: 'category',
              label: 'Queues',
              items: [
                'qstash/api/queues/upsert',
                'qstash/api/queues/remove',
                'qstash/api/queues/list',
                'qstash/api/queues/get',
                'qstash/api/queues/pause',
                'qstash/api/queues/resume',
              ],
            },
            {
              type: 'category',
              label: 'Schedules',
              items: [
                'qstash/api/schedules/create',
                'qstash/api/schedules/get',
                'qstash/api/schedules/list',
                'qstash/api/schedules/remove',
                'qstash/api/schedules/pause',
                'qstash/api/schedules/resume',
              ],
            },
            {
              type: 'category',
              label: 'Signing Keys',
              items: [
                'qstash/api/signingKeys/get',
                'qstash/api/signingKeys/rotate',
              ],
            },
            {
              type: 'category',
              label: 'Events',
              items: ['qstash/api/events/list'],
            },
            {
              type: 'category',
              label: 'Dead Letter Queues',
              items: [
                'qstash/api/dlq/listMessages',
                'qstash/api/dlq/getMessage',
                'qstash/api/dlq/deleteMessage',
                'qstash/api/dlq/deleteMessages',
              ],
            },
            {
              type: 'category',
              label: 'LLM',
              items: ['qstash/api/llm/create'],
            },
            'qstash/api/api-ratelimiting',
          ],
        },
        {
          type: 'category',
          label: 'SDKs',
          items: [
            {
              type: 'category',
              label: 'Typescript',
              items: [
                'qstash/sdks/ts/overview',
                'qstash/sdks/ts/gettingstarted',
                {
                  type: 'category',
                  label: 'Examples',
                  items: [
                    'qstash/sdks/ts/examples/overview',
                    'qstash/sdks/ts/examples/publish',
                    'qstash/sdks/ts/examples/schedules',
                    'qstash/sdks/ts/examples/url-groups',
                    'qstash/sdks/ts/examples/dlq',
                    'qstash/sdks/ts/examples/events',
                    'qstash/sdks/ts/examples/messages',
                    'qstash/sdks/ts/examples/receiver',
                    'qstash/sdks/ts/examples/queues',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Python',
              items: [
                'qstash/sdks/py/overview',
                'qstash/sdks/py/gettingstarted',
                {
                  type: 'category',
                  label: 'Examples',
                  items: [
                    'qstash/sdks/py/examples/overview',
                    'qstash/sdks/py/examples/publish',
                    'qstash/sdks/py/examples/schedules',
                    'qstash/sdks/py/examples/url-groups',
                    'qstash/sdks/py/examples/dlq',
                    'qstash/sdks/py/examples/events',
                    'qstash/sdks/py/examples/messages',
                    'qstash/sdks/py/examples/keys',
                    'qstash/sdks/py/examples/receiver',
                    'qstash/sdks/py/examples/queues',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer API',
      items: [
        'devops/developer-api/introduction',
        'devops/developer-api/authentication',
        'devops/developer-api/http_status_codes',
        {
          type: 'category',
          label: 'Redis',
          items: [
            'devops/developer-api/redis/create_database',
            'devops/developer-api/redis/create_database_global',
            'devops/developer-api/redis/delete_database',
            'devops/developer-api/redis/list_databases',
            'devops/developer-api/redis/get_database',
            'devops/developer-api/redis/get_database_stats',
            'devops/developer-api/redis/update_regions',
            'devops/developer-api/redis/reset_password',
            'devops/developer-api/redis/rename_database',
            'devops/developer-api/redis/enable_tls',
            'devops/developer-api/redis/enable_eviction',
            'devops/developer-api/redis/disable_eviction',
            'devops/developer-api/redis/enable_autoscaling',
            'devops/developer-api/redis/disable_autoscaling',
            'devops/developer-api/redis/moveto_team',
            {
              type: 'category',
              label: 'Backup',
              items: [
                'devops/developer-api/redis/backup/create_backup',
                'devops/developer-api/redis/backup/delete_backup',
                'devops/developer-api/redis/backup/restore_backup',
                'devops/developer-api/redis/backup/list_backup',
                'devops/developer-api/redis/backup/enable_dailybackup',
                'devops/developer-api/redis/backup/disable_dailybackup',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Kafka',
          items: [
            {
              type: 'category',
              label: 'Clusters',
              items: [
                'devops/developer-api/kafka/clusters/create',
                'devops/developer-api/kafka/clusters/delete',
                'devops/developer-api/kafka/clusters/list',
                'devops/developer-api/kafka/clusters/get',
                'devops/developer-api/kafka/clusters/stats',
                'devops/developer-api/kafka/clusters/rename',
                'devops/developer-api/kafka/clusters/reset_password',
              ],
            },
            {
              type: 'category',
              label: 'Topics',
              items: [
                'devops/developer-api/kafka/topics/create',
                'devops/developer-api/kafka/topics/delete',
                'devops/developer-api/kafka/topics/list',
                'devops/developer-api/kafka/topics/get',
                'devops/developer-api/kafka/topics/stats',
                'devops/developer-api/kafka/topics/reconfigure',
              ],
            },
            {
              type: 'category',
              label: 'Credentials',
              items: [
                'devops/developer-api/kafka/credentials/create',
                'devops/developer-api/kafka/credentials/delete',
                'devops/developer-api/kafka/credentials/list',
              ],
            },
            {
              type: 'category',
              label: 'Connectors',
              items: [
                'devops/developer-api/kafka/connectors/create',
                'devops/developer-api/kafka/connectors/delete',
                'devops/developer-api/kafka/connectors/list',
                'devops/developer-api/kafka/connectors/get',
                'devops/developer-api/kafka/connectors/start',
                'devops/developer-api/kafka/connectors/pause',
                'devops/developer-api/kafka/connectors/restart',
                'devops/developer-api/kafka/connectors/reconfigure',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Vector',
          items: [
            'devops/developer-api/vector/create_index',
            'devops/developer-api/vector/delete_index',
            'devops/developer-api/vector/list_indices',
            'devops/developer-api/vector/get_index',
            'devops/developer-api/vector/transfer_index',
            'devops/developer-api/vector/rename_index',
            'devops/developer-api/vector/reset_index_passwords',
            'devops/developer-api/vector/set_index_plan',
          ],
        },
        {
          type: 'category',
          label: 'Teams',
          items: [
            'devops/developer-api/teams/create_team',
            'devops/developer-api/teams/delete_team',
            'devops/developer-api/teams/list_teams',
            'devops/developer-api/teams/add_team_member',
            'devops/developer-api/teams/delete_team_member',
            'devops/developer-api/teams/get_team_members',
          ],
        },
        {
          type: 'category',
          label: 'DevOps',
          items: [
            {
              type: 'category',
              label: 'Terraform',
              items: [
                'devops/terraform/overview',
                {
                  type: 'category',
                  label: 'Resources',
                  items: [
                    'devops/terraform/resources/upstash_kafka_cluster',
                    'devops/terraform/resources/upstash_kafka_connector',
                    'devops/terraform/resources/upstash_kafka_credential',
                    'devops/terraform/resources/upstash_kafka_topic',
                    'devops/terraform/resources/upstash_qstash_endpoint',
                    'devops/terraform/resources/upstash_qstash_schedule',
                    'devops/terraform/resources/upstash_qstash_topic',
                    'devops/terraform/resources/upstash_redis_database',
                    'devops/terraform/resources/upstash_team',
                  ],
                },
                {
                  type: 'category',
                  label: 'Data Sources',
                  items: [
                    'devops/terraform/data_sources/upstash_kafka_cluster_data',
                    'devops/terraform/data_sources/upstash_kafka_connector_data',
                    'devops/terraform/data_sources/upstash_kafka_credential_data',
                    'devops/terraform/data_sources/upstash_kafka_topic_data',
                    'devops/terraform/data_sources/upstash_qstash_endpoint_data',
                    'devops/terraform/data_sources/upstash_qstash_schedule_data',
                    'devops/terraform/data_sources/upstash_qstash_topic_data',
                    'devops/terraform/data_sources/upstash_redis_database_data',
                    'devops/terraform/data_sources/upstash_team_data',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Pulumi',
              items: ['devops/pulumi/overview'],
            },
            {
              type: 'category',
              label: 'CLI',
              items: ['devops/cli/overview'],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflow',
      items: [
        'workflow/getstarted',
        {
          type: 'category',
          label: 'Quickstarts',
          items: [
            'workflow/quickstarts/platforms',
            'workflow/quickstarts/vercel-nextjs',
            'workflow/quickstarts/cloudflare-workers',
            'workflow/quickstarts/nuxt',
            'workflow/quickstarts/solidjs',
            'workflow/quickstarts/svelte',
            'workflow/quickstarts/hono',
            'workflow/quickstarts/express',
            'workflow/quickstarts/astro',
          ],
        },
        {
          type: 'category',
          label: 'Basics',
          items: [
            'workflow/basics/serve',
            'workflow/basics/context',
            'workflow/basics/client',
            'workflow/basics/how',
            'workflow/basics/caveats',
          ],
        },
        {
          type: 'category',
          label: 'How To',
          items: [
            'workflow/howto/start',
            'workflow/howto/failures',
            'workflow/howto/cancel',
            'workflow/howto/events',
            'workflow/howto/monitor',
            'workflow/howto/security',
            'workflow/howto/parallel-runs',
            'workflow/howto/schedule',
            'workflow/howto/changes',
            'workflow/howto/local-development',
            'workflow/howto/use-webhooks',
            'workflow/migration',
          ],
        },
        {
          type: 'category',
          label: 'REST API',
          items: [
            'workflow/rest/runs/notify',
            'workflow/rest/runs/cancel',
            'workflow/rest/runs/bulk-cancel',
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          items: [
            'workflow/integrations/openai',
            'workflow/integrations/anthropic',
            'workflow/integrations/resend',
            'workflow/integrations/ai-sdk',
          ],
        },
        {
          type: 'category',
          label: 'Examples',
          items: [
            'workflow/examples/allInOne',
            'workflow/examples/waitForEvent',
            'workflow/examples/customerOnboarding',
            'workflow/examples/authWebhook',
            'workflow/examples/paymentRetry',
            'workflow/examples/eCommerceOrderFulfillment',
            'workflow/examples/imageProcessing',
            'workflow/examples/customRetry',
          ],
        },
        'workflow/pricing',
        {
          type: 'category',
          label: 'Troubleshooting',
          items: [
            'workflow/troubleshooting/general',
            'workflow/troubleshooting/vercel',
          ],
        },
        'workflow/changelog',
        'workflow/roadmap',
      ],
    },
  ],


};

export default sidebars;
